### ISSUE TITLE
Geo / getArriveStop - Unrecognized client

### ISSUE THREAD

**Issue by DestroyerIV** [Lorengamboa/EMT-library#1]
Hello, first of all I congratulate you on this API that I am currently a user of. I'm currently trying to work with the getArriveStop method but it returns the following message: Unrecognized client. Should I request another type of Token? I have used other methods of ('bus') and they work perfectly. If you could help me, I would appreciate it. I show you the code in case it was technical error.

```js
var EMT = require('emt-bus');
EMTToken = new EMT('idClient', 'passKey')

var geo = EMTToken('geo')
geo.getArriveStop('codeStop', 'ES').then(function(result) {
                console.log(result)
 })
```
While in console it shows the following:
```js
{ReturnCode: '4', 
Description: 'Unrecognized client'}
```
Thanks in advance

**Comment by Lorengamboa** [comment]
Ill take note of that and test it myself.

Ill give u a solution to the problem soon.

**Comment by Lorengamboa** [comment]
The problem lays on how the pass data is sent to the API service layer.
```js
var formData = {
      "cultureInfo": "ES",
       "idStop": "636"
 };
geo.getArriveStop(formData)
       .then(function (res) {
       // res
  });
```

Follow the example I pasted. The documentation is a bit off the road but if I see more issues to come up I'll make sure its clean and updated.

Please, once you try this solution let me know tho.

**Comment by DestroyerIV** [comment]
@Lorengamboa 
Working correctly. If you think it is appropriate to use the Spanish language to speak and understand each other better, let us know. Thanks for your time and work

One last question, if it is not annoying. In what unit of time is 'busTimeLeft?'

**Comment by Lorengamboa** [comment]
@DestroyerIV Por lo menos en mis repositorios no existe ningún idioma  obligatorio que ha de ser usado. Cualquier duda, adelante.

**Comment by DestroyerIV** [comment]
@Lorengamboa 
Se agradece poder hablar el idioma materno jajajaja
Una ultima duda, en que unidad de tiempo se basa la propiedad 'busTimeLeft?'

**Comment by Lorengamboa** [comment]
@DestroyerIV Haz las preguntas que hagan falta!
Se mide en segundos (int)
El problema y reconozco que la documentación es pobre y esta totalmente incompleta.

**Comment by DestroyerIV** [comment]
No me importaría ayudarte a actualizarla, poco a poco y con tiempo.
A partir del primer ejemplo, ya se que debo jugar con el posicionamiento de los requisitos de cada método.
Me devuelve, por ejemplo 214, como podría convertirlo a una sola cifra? 

Perdona mi ignorancia, de verdad.

**Comment by Lorengamboa** [comment]
Tranquilo nadie nace sabiendo.

Pásame el payload que le pasaste al método que usaste.

**Comment by Lorengamboa** [comment]
En caso de lo que te devuelva sean los segundos, prueba pasarlo a minutos.

const segundos = Math.floor(tiempo / 60);

- sustituye la variable tiempo el tiempo estimado que te haya devuelto el método.
- el resultado que obtengas esta acotado.

**Comment by DestroyerIV** [comment]
Esto es lo que me devuelve la funcion `result`

```
{ stopId: 1105,
  lineId: '103',
  isHead: 'False',
  destination: 'ECOBULEVAR',
  busId: '6821',
  busTimeLeft: 50,
  busDistance: 116,
  longitude: -3.6618715809846,
  latitude: 40.388149183923,
  busPositionType: 2 }
```

**Comment by Lorengamboa** [comment]
Que buscas obtener aqui?

**Comment by Lorengamboa** [comment]
En cuanto a la doc estaría fantástico si puedes ayudarme, haces un PR y lo reviso.

Un saludo.

**Comment by DestroyerIV** [comment]
Utilizando el Math.floor((result.arrives[i].busTimeLeft) / 60) , en los dos primeros resultados me los muestra correctamente, pero en los dos siguiente que le siguen, me muestra 16666

En el result, busco los atributos de lineId, destination, busTimeLeft y busDistance. 

Actualmente ya tengo todos menos busTimeLeft, que como cito anteriormente, los que sobrepasan los 20 minutos me los muestra como 16666

**Comment by DestroyerIV** [comment]
Respecto a la Doc, comenzaré a hacer pruebas para descartar errores a la hora de organizar el orden de las propiedades que cada método requiere.

**Comment by Lorengamboa** [comment]
Time to arrive in seconds (if all 9, means more than 20 minutes) (if 0 bus in the stop)

**Comment by Lorengamboa** [comment]
@DestroyerIV si quieres hacer pruebas puedes aprovechar y continuar el archivo de test.js y apoyandote en ello para completar la doc.
si existe un problema de código, abres issue y la resuelvo.

**Comment by Lorengamboa** [comment]
Te paso el link que devuelve un archivo con la doc.

http://opendata.emtmadrid.es/Documentos/Opendata-v-1-12.aspx

**Comment by Lorengamboa** [comment]
La prueba que te devolvió 16666 que tiempo te dio?

**Comment by DestroyerIV** [comment]
@Lorengamboa 
Si tienes Telegram, te dejo mi alias para que tengamos un contacto mas fluido @NeganLucille

Respecto al tema de 16666, solo lo muestra cuando el tiempo es mas de 20 minutos, estoy añadiendo un if que controle esa circunstancia sin resultados.

**Comment by Lorengamboa** [comment]
@DestroyerIV no tengo Telegram.

tengo discord.

**Comment by Lorengamboa** [comment]
Loren#8221 es el discord que uso actualmente.
