### ISSUE TITLE
Uncontrolled function GEO - getRouteLines is not a function

### ISSUE THREAD

**Issue by DestroyerIV** [Lorengamboa/EMT-library#2]
Testing the different methods, I noticed that the getRouteLinesRoute function of the GEO method is not controlled, so it can not show results.

In console it shows me the following:
`geo.getRouteLinesRoute is not a function`

I hope to help. Thank you very much in advance

**Comment by Lorengamboa** [comment]
Oh I might have missed including that method to its own service by mistake.

I'll take note of it. Thanks anyways, ill make changes soon!
