### ISSUE TITLE
Exposición de credenciales

### ISSUE THREAD

**Issue by axl89** [Lorengamboa/EMT-library#3]
https://github.com/Lorengamboa/EMT-library/blob/ca92c3550c32524cce649784a71368ee46484648/.env#L4

@Lorengamboa : Creo que esto es información confidencial y no debería ser parte del código 👎

Te recomiendo que mires cómo modificar la historia de git, ya que con borrarlos en un commit no basta. 

Una vez lo hayas quitado y modificado la historia de git, puedes usar programas como truffleHog para ver si quedan cosillas feas por el repo.

**Comment by Lorengamboa** [comment]
> [EMT-library/.env](https://github.com/Lorengamboa/EMT-library/blob/ca92c3550c32524cce649784a71368ee46484648/.env#L4)
> 
> Line 4 in [ca92c35](/Lorengamboa/EMT-library/commit/ca92c3550c32524cce649784a71368ee46484648)
> 
>  PASS_KEY = "744FDBE6-0C89-43EF-8114-536BF14C6E51" 
> @Lorengamboa : Creo que esto es información confidencial y no debería ser parte del código 
> 
> Te recomiendo que mires cómo modificar la historia de git, ya que con borrarlos en un commit no basta.
> 
> Una vez lo hayas quitado y modificado la historia de git, puedes usar programas como truffleHog para ver si quedan cosillas feas por el repo.

Muchas gracias! Eso voy a hacer. :)

**Comment by Lorengamboa** [comment]
> [EMT-library/.env](https://github.com/Lorengamboa/EMT-library/blob/ca92c3550c32524cce649784a71368ee46484648/.env#L4)
> 
> Line 4 in [ca92c35](/Lorengamboa/EMT-library/commit/ca92c3550c32524cce649784a71368ee46484648)
> 
>  PASS_KEY = "744FDBE6-0C89-43EF-8114-536BF14C6E51" 
> @Lorengamboa : Creo que esto es información confidencial y no debería ser parte del código 
> 
> Te recomiendo que mires cómo modificar la historia de git, ya que con borrarlos en un commit no basta.
> 
> Una vez lo hayas quitado y modificado la historia de git, puedes usar programas como truffleHog para ver si quedan cosillas feas por el repo.

Muchas gracias! Eso voy a hacer. :)

**Comment by Lorengamboa** [comment]
@axl89 Muchas gracias! Eso voy a hacer. :)
