### ISSUE TITLE
New version of open data of Madrid

### ISSUE THREAD

**Issue by DestroyerIV** [Lorengamboa/EMT-library#4]
Hi, my question is if you plan to upgrade to the [new API](https://apidocs.emtmadrid.es/). I would like to help develop it but I do not have the necessary knowledge.

Thanks in advance.
a greeting

**Comment by Lorengamboa** [comment]
Hey,
of course go ahead and start making it. Don't worry whether or not is ok.
You can start by adding the new url codebase (https://openapi.emtmadrid.es) to the following source file:
 - EMT-library/src/config/url/index.js

Then move on into adding new methods to the interface and so on.
Once you have something make pull request and we'll have a look at it

**Comment by Lorengamboa** [comment]
Try giving the 'Hello' category a try. 

seems like a reasonable thing to start with.

**Comment by DestroyerIV** [comment]
> Hey,
> of course go ahead and start making it. Don't worry whether or not is ok.
> You can start by adding the new url codebase (https://openapi.emtmadrid.es) to the following source file:
> 
>     * EMT-library/src/config/url/index.js
> 
> 
> Then move on into adding new methods to the interface and so on.
> Once you have something make pull request and we'll have a look at it

What do you need in this file?
